#!/bin/bash

defined () {
    [[ ${!1-X} == ${!1-Y} ]]
}

has_value () {
    if defined $1; then
        if [[ -n ${!1} ]]; then
            return 0
        fi
    fi
    return 1
}

error=0

if ! has_value USER_UID; then
  echo "You must set USER_UID as a docker env var"
  error=1
fi

if ! has_value USER_GID; then
  echo "You must set USER_GID as a docker env var"
  error=1
fi

if ! has_value VERSION; then
  echo "You must set VERSION as a docker env var (syncthing version to base this on)"
  error=1
fi

if [[ $error > 0 ]]; then
  exit 1
fi

if [ ! -e /syncthing/syncthing ]; then
cd /
wget -O /syncthing.tar.gz https://github.com/syncthing/syncthing/releases/download/v${VERSION}/syncthing-linux-amd64-v${VERSION}.tar.gz && \
  tar xvf /syncthing.tar.gz && \
  mv /syncthing-linux-amd64-v${VERSION}/syncthing /syncthing/syncthing
fi
groupadd --gid $USER_GID syncthing
useradd -d /Sync -m syncthing --uid $USER_UID --gid $USER_GID --shell /bin/bash
/syncthing/syncthing -upgrade
chown -R syncthing:syncthing /Sync /Config
su -c "/syncthing/syncthing -home /Config -gui-address=https://0.0.0.0:8080 -no-browser" syncthing