#!/bin/bash

defined () {
    [[ ${!1-X} == ${!1-Y} ]]
}

has_value () {
    if defined $1; then
        if [[ -n ${!1} ]]; then
            return 0
        fi
    fi
    return 1
}

error=0

if ! has_value USER_UID; then
  echo "You must set USER_UID as a docker env var"
  error=1
fi

if ! has_value USER_GID; then
  echo "You must set USER_GID as a docker env var"
  error=1
fi

if ! has_value VERSION; then
  echo "You must set VERSION as a docker env var (syncthing version to base this on)"
  error=1
fi

if [[ $error > 0 ]]; then
  exit 1
fi

if [ ! -e /syncthing/syncthing ]; then
  cd /
  wget --no-check-certificate -O /syncthing.tar.gz https://github.com/syncthing/syncthing/releases/download/v${VERSION}/syncthing-linux-amd64-v${VERSION}.tar.gz && \
  tar xvf /syncthing.tar.gz && \
  mv /syncthing-linux-amd64-v${VERSION}/syncthing /syncthing/syncthing
fi

addgroup -g $USER_GID syncthing
adduser -h /Sync -u $USER_UID -D -G syncthing -s /bin/bash syncthing
/syncthing/syncthing -upgrade
chown -R syncthing:syncthing /Sync /Config /syncthing
exec su -c "exec /syncthing/syncthing -home /Config -gui-address=https://0.0.0.0:8384 -no-browser" syncthing
